"use client"

import PageHeader from "@/components/PageHeader"
import { FileText, TrendingUp, Target, Lightbulb } from "lucide-react"

const REPORT = {
  week: "May 12 – 18, 2026",
  wins: [
    "M3K1 TikTok crossed 800 followers — up 32% in 2 weeks",
    "Fortis Mane Instagram hit 1,240 — strongest brand by followers",
    "Merch net positive for second consecutive month ($87 profit)",
    "Legal scan pipeline cleared 5 of 6 assets within 24h",
  ],
  misses: [
    "Post cadence fell to 11/week vs 21 target — 3 missed days",
    "XRXS Worship snippet flagged for potential copyright — post blocked",
    "Philosopher Stoned YouTube — only 1 upload this month",
    "M3K1 merch drop delayed (design still in AI queue)",
  ],
  priorities: [
    "Increase post frequency: schedule 3/day across brands via n8n",
    "Resolve XRXS copyright flag — rerecord or clear sample",
    "Upload Philosopher Ep.7 and clip into 5 TikTok shorts",
    "Launch M3K1 merch drop — push design generation today",
    "Set up TikTok API connection for automated posting",
  ],
  insight: "XRXS has the highest engagement rate (7.8%) but lowest post volume. This is a sleeping giant — consistent posting could triple your reach within 30 days without paid ads.",
}

export default function BoardroomPage() {
  return (
    <div>
      <PageHeader
        title="Boardroom"
        subtitle="Weekly executive briefing — AI-generated performance report"
        actions={
          <button
            className="flex items-center gap-2 text-xs px-3 py-2 rounded-lg font-medium transition-all hover:opacity-80"
            style={{ background: "var(--surface-2)", color: "var(--foreground)", border: "1px solid var(--border)" }}
          >
            <FileText size={12} /> Export PDF
          </button>
        }
      />

      {/* Report header */}
      <div
        className="rounded-xl p-5 mb-6"
        style={{ background: "var(--surface)", border: "1px solid var(--accent-gold)44" }}
      >
        <div className="flex items-center gap-2 mb-1">
          <div
            className="w-6 h-6 rounded flex items-center justify-center text-xs font-bold"
            style={{ background: "var(--accent-gold)", color: "#0a0a0f" }}
          >
            N
          </div>
          <p className="text-sm font-bold" style={{ color: "var(--accent-gold)" }}>NATIVE OS — Weekly Executive Brief</p>
        </div>
        <p className="text-xs" style={{ color: "var(--muted)" }}>Period: {REPORT.week} · Generated by AI advisor</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mb-4">
        {/* Wins */}
        <div className="rounded-xl p-4" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
          <div className="flex items-center gap-2 mb-3">
            <TrendingUp size={15} style={{ color: "var(--accent-green)" }} />
            <p className="text-sm font-semibold" style={{ color: "var(--accent-green)" }}>Wins This Week</p>
          </div>
          <ul className="space-y-2">
            {REPORT.wins.map((w, i) => (
              <li key={i} className="flex items-start gap-2">
                <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: "var(--accent-green)" }} />
                <span className="text-xs" style={{ color: "var(--muted)" }}>{w}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Misses */}
        <div className="rounded-xl p-4" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
          <div className="flex items-center gap-2 mb-3">
            <Target size={15} style={{ color: "var(--accent-red)" }} />
            <p className="text-sm font-semibold" style={{ color: "var(--accent-red)" }}>Gaps to Address</p>
          </div>
          <ul className="space-y-2">
            {REPORT.misses.map((m, i) => (
              <li key={i} className="flex items-start gap-2">
                <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: "var(--accent-red)" }} />
                <span className="text-xs" style={{ color: "var(--muted)" }}>{m}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Priorities */}
      <div className="rounded-xl p-4 mb-4" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
        <p className="text-sm font-semibold mb-3" style={{ color: "var(--foreground)" }}>Top 5 Priorities — Next 7 Days</p>
        <div className="space-y-2">
          {REPORT.priorities.map((p, i) => (
            <div key={i} className="flex items-start gap-3">
              <div
                className="w-5 h-5 rounded flex items-center justify-center text-xs font-bold flex-shrink-0 mt-0.5"
                style={{ background: "var(--accent-gold)33", color: "var(--accent-gold)" }}
              >
                {i + 1}
              </div>
              <p className="text-sm" style={{ color: "var(--foreground)" }}>{p}</p>
            </div>
          ))}
        </div>
      </div>

      {/* AI Insight */}
      <div
        className="rounded-xl p-4"
        style={{ background: "#8b5cf620", border: "1px solid #8b5cf644" }}
      >
        <div className="flex items-start gap-2">
          <Lightbulb size={15} style={{ color: "#8b5cf6", marginTop: 2, flexShrink: 0 }} />
          <div>
            <p className="text-xs font-semibold mb-1" style={{ color: "#8b5cf6" }}>AI Insight of the Week</p>
            <p className="text-sm" style={{ color: "var(--foreground)" }}>{REPORT.insight}</p>
          </div>
        </div>
      </div>
    </div>
  )
}
